spring:
  application:
    name: eureka-server
server:
  port: 7001
eureka:
  instance:
    hostname: eurekaserver7001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server7002:7002/eureka/
