server:
  port: 9001
  max-http-header-size: 10240
  
#mysql数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exbox?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    filters: wall,mergeStat
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源